---
title: Promise all 错误处理
date: 2021-03-31
categories: 
 - 面试
tags:
 - 代码实现
sidebar: 'auto'
---


> 题目来源<https://jsgodroad.com/questions/detail?id=11>

* 异步请求通过 Promise.all 处理，怎么让其中失败的所有请求重试。
```js
Promise.all([A, B, C, D])
// 4 个请求完成后发现 AD 请求失败了，如果让失败的请求重试
```


```js
async function allSuccessPromise(...primiseFuncs) {
  const failPromises = []
  const res = await Promise.all(primiseFuncs.map(async p => {
    try {
      // 要求执行的promise成功必须resolve一个真值，否则认为失败
      const successed = await p()
      if (successed) {
        return successed
      }
      failPromises.push(p)
    } catch (err) {
      failPromises.push(p)
    }
  }))
  return [...res.filter(Boolean)].concat(failPromises.length ? await allSuccessPromise(...failPromises) : [])
}

function a () {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (Math.random() < 0.5) { // 设定一个成功或者失败的条件
        resolve('A');
      } else {
        reject()
      }
    }, Math.random() * 2000);
  })
}
function b () {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (Math.random() < 0.5) { // 设定一个成功或者失败的条件
        resolve('B');
      } else {
        reject()
      }
    }, 3000);
  })
}
function c () {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (Math.random() < 0.5) { // 设定一个成功或者失败的条件
        resolve('C');
      } else {
        reject()
      }
    }, 1500);
  })
}
;(async() => {
  const res = await allSuccessPromise(a, b, c)
  // 缺陷：返回的结果可能不按顺序
  console.log(res);
})()
```